# ***ASSIGNMENT: 2 NUMPY***

# TASK 1: Creating Arrays

In [4]:
# 1. Write a Python program to:
#  Create a 1D NumPy array of 10 integers ranging from 1 to 10.
#  Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
#  Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
# 2. Display the shape, size, and datatype of each array.

import numpy as np

# 1D array
arr_1d = np.arange(1, 11)
print("1D Array:")
print(arr_1d)
print("Shape:", arr_1d.shape)
print("Size:", arr_1d.size)
print("Datatype:", arr_1d.dtype)
print("-" * 20)

# 2D array
arr_2d = np.arange(1, 10).reshape(3, 3)
print("2D Array:")
print(arr_2d)
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Datatype:", arr_2d.dtype)
print("-" * 20)

# 3D array
arr_3d = np.random.rand(3, 5, 3)
print("3D Array:")
print(arr_3d)
print("Shape:", arr_3d.shape)
print("Size:", arr_3d.size)
print("Datatype:", arr_3d.dtype)
print("-" * 20)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Datatype: int64
--------------------
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Datatype: int64
--------------------
3D Array:
[[[0.77875493 0.26729254 0.47217493]
  [0.42950503 0.79511884 0.75166666]
  [0.2697487  0.46370063 0.96069977]
  [0.49431626 0.53530666 0.06385446]
  [0.30087785 0.80203188 0.40176933]]

 [[0.24093856 0.92133314 0.5905683 ]
  [0.30803601 0.04604434 0.59309616]
  [0.27566662 0.88376449 0.39240762]
  [0.20542201 0.90224168 0.07499489]
  [0.85744606 0.77657672 0.25723833]]

 [[0.44335718 0.16007909 0.91327651]
  [0.8965168  0.73480176 0.98950499]
  [0.25266714 0.86384264 0.31233209]
  [0.56238845 0.27121982 0.29712029]
  [0.5895866  0.62329395 0.82698609]]]
Shape: (3, 5, 3)
Size: 45
Datatype: float64
--------------------


#Task 2: Array Indexing and Slicing

In [5]:
# 1. Create a NumPy array from the following list:
# data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# 2. Write a Python program to:
# o Retrieve the first three elements of the array.
# o Retrieve every alternate element of the array.
# o Reverse the array.
# 3. Perform the above operations and display the results.

# Task 2: Array Indexing and Slicing
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)

first_three = arr[:3]
print("First three elements:", first_three)

alternate_elements = arr[::2]
print("Every alternate element:", alternate_elements)

reversed_array = arr[::-1]
print("Reversed array:", reversed_array)

First three elements: [10 20 30]
Every alternate element: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


#Task 3: Mathematical Operations

In [7]:
# 1. Create two NumPy arrays, A and B, each with 5 random integers
# between 1 and 20.
# 2. Write a Python program to:
# o Add, subtract, multiply, and divide the two arrays element
# wise.
# o Compute the dot product of the arrays.
# o Find the mean, median, standard deviation, and variance of
# array A.
# o Identify the maximum and minimum values in array B and
# their indices.


A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)
print("Array A:", A)
print("Array B:", B)

# Element-wise operations
print("Addition (A + B):", A + B)
print("Subtraction (A - B):", A - B)
print("Multiplication (A * B):", A * B)
print("Division (A / B):", A / B)

# Dot product
dot_product = np.dot(A, B)
print("Dot Product (A . B):", dot_product)

# Statistics for array A
print("Mean of A:", np.mean(A))
print("Median of A:", np.median(A))
print("Standard Deviation of A:", np.std(A))
print("Variance of A:", np.var(A))

# Max/Min for array B
max_B = np.max(B)
min_B = np.min(B)
max_index_B = np.argmax(B)
min_index_B = np.argmin(B)
print("Maximum value in B:", max_B, "at index", max_index_B)
print("Minimum value in B:", min_B, "at index", min_index_B)

Array A: [10 18  5 12  2]
Array B: [ 5 13  3  8 13]
Addition (A + B): [15 31  8 20 15]
Subtraction (A - B): [  5   5   2   4 -11]
Multiplication (A * B): [ 50 234  15  96  26]
Division (A / B): [2.         1.38461538 1.66666667 1.5        0.15384615]
Dot Product (A . B): 421
Mean of A: 9.4
Median of A: 10.0
Standard Deviation of A: 5.571355310873647
Variance of A: 31.04
Maximum value in B: 13 at index 1
Minimum value in B: 3 at index 2


# Task 4: Reshaping and Transposing

In [8]:
# 1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
# 2. Write a Python program to:
# o Reshape the array into a 2D array of shape (4, 3).
# o Reshape the array into a 3D array of shape (2, 2, 3).
# o Transpose the reshaped 2D array and display its shape.

arr_5 = np.arange(1, 13)
print("Original 1D array (1-12):")
print(arr_5)
print("-" * 20)

arr_2d_reshaped = arr_5.reshape(4, 3)
print("Reshaped to 2D array (4, 3):")
print(arr_2d_reshaped)
print("Shape:", arr_2d_reshaped.shape)
print("-" * 20)

arr_3d_reshaped = arr_5.reshape(2, 2, 3)
print("Reshaped to 3D array (2, 2, 3):")
print(arr_3d_reshaped)
print("Shape:", arr_3d_reshaped.shape)
print("-" * 20)

arr_2d_transposed = arr_2d_reshaped.transpose()
print("Transposed 2D array:")
print(arr_2d_transposed)
print("Shape:", arr_2d_transposed.shape)
print("-" * 20)

Original 1D array (1-12):
[ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------------
Reshaped to 2D array (4, 3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
--------------------
Reshaped to 3D array (2, 2, 3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
--------------------
Transposed 2D array:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape: (3, 4)
--------------------


# Task 5: Boolean Masking and Filtering

In [11]:
# 1. Create a NumPy array with 15 random integers between 10 and 50.
# 2. Write a Python program to:
# o Find all elements greater than 25.
# o Replace all elements less than 30 with 0.
# o Count the number of elements divisible by 5.

arr_task5 = np.random.randint(10, 51, 15)
print("Original array:", arr_task5)
print("-" * 20)

greater_than_25 = arr_task5[arr_task5 > 25]
print("Elements greater than 25:", greater_than_25)
print("-" * 20)

arr_task5[arr_task5 < 30] = 0
print("Array after replacing elements less than 30 with 0:", arr_task5)
print("-" * 20)


divisible_by_5_count = np.sum(arr_task5 % 5 == 0)
print("Number of elements divisible by 5:", divisible_by_5_count)
print("-" * 20)

Original array: [48 36 27 47 32 19 30 22 22 36 33 50 50 21 30]
--------------------
Elements greater than 25: [48 36 27 47 32 30 36 33 50 50 30]
--------------------
Array after replacing elements less than 30 with 0: [48 36  0 47 32  0 30  0  0 36 33 50 50  0 30]
--------------------
Number of elements divisible by 5: 9
--------------------


#Task 6: Working with Built-in Functions

In [12]:
# 1. Use NumPy's built-in functions to:
# o Create an array of 10 equally spaced values between 0 and 1.
# o Create an identity matrix of size 4x4.
# o Generate a 1D array of 20 random integers between 1 and 100,
# sort it, and find the 5 largest elements.

linspace_array = np.linspace(0, 1, 10)
print("Array of 10 equally spaced values between 0 and 1:")
print(linspace_array)
print("-" * 20)

identity_matrix = np.eye(4)
print("Identity matrix of size 4x4:")
print(identity_matrix)
print("-" * 20)

random_integers = np.random.randint(1, 101, 20)
print("Original random integers array:")
print(random_integers)

sorted_random_integers = np.sort(random_integers)
print("Sorted random integers array:")
print(sorted_random_integers)

largest_5_elements = sorted_random_integers[-5:]
print("The 5 largest elements:")
print(largest_5_elements)
print("-" * 20)

Array of 10 equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
--------------------
Identity matrix of size 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------
Original random integers array:
[74  9 89 39 32 81 26 60  1 62 71 96 11 63 33  9 96 82 92 91]
Sorted random integers array:
[ 1  9  9 11 26 32 33 39 60 62 63 71 74 81 82 89 91 92 96 96]
The 5 largest elements:
[89 91 92 96 96]
--------------------


#Task 7: Generic

In [18]:
# 1. Create a Python program that:
# o Generates two large random arrays of size (100, 100).
# o Performs matrix multiplication on the two arrays.
# o Finds the determinant and inverse of the resulting matrix (if
# possible).
# o Measures the time taken to complete these operations.

import time


start_time = time.time()

size = (100, 100)
array1 = np.random.rand(*size)
array2 = np.random.rand(*size)

print(f"Generated two random arrays of size {size}")


result_matrix = np.dot(array1, array2)
print("Performed matrix multiplication")

determinant = np.linalg.det(result_matrix)
print(f"Determinant of the resulting matrix: {determinant}")

try:
  inverse_matrix = np.linalg.inv(result_matrix)
  print("Found the inverse of the resulting matrix")
except np.linalg.LinAlgError:
  inverse_matrix = None
  print("Could not find the inverse (matrix is singular)")

end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for operations: {time_taken:.4f} seconds")
print("-" * 20)

Generated two random arrays of size (100, 100)
Performed matrix multiplication
Determinant of the resulting matrix: -1.2561284165182584e+50
Found the inverse of the resulting matrix
Time taken for operations: 0.0465 seconds
--------------------
